/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 17.08.2026 12:48:40

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 1648;
#else
constexpr int kTensorArenaSize = 624;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,207 } };
const TfArray<1, float> quant0_scale = { 1, { 0.78125113248825073, } };
const TfArray<1, int> quant0_zero = { 1, { -120 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[4] = { 3, 20, -32, -3, };
const TfArray<1, int> tensor_dimension1 = { 1, { 4 } };
const TfArray<1, float> quant1_scale = { 1, { 0.002746162936091423, } };
const TfArray<1, int> quant1_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant1 = { (TfLiteFloatArray*)&quant1_scale, (TfLiteIntArray*)&quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data2[4*30] = { 
  -5, -27, -15, -10, 85, 10, 28, 41, -25, -17, 31, -38, -67, -127, -42, -16, -2, 5, -26, 28, -25, -54, -16, 14, 16, -5, -6, 23, 22, -57, 
  -6, -72, -61, -5, 12, 20, -75, -30, -72, -10, 16, 41, 35, 45, 16, -9, -69, 19, 27, -48, 0, -11, 2, 17, -44, 81, 6, -25, 25, -26, 
  -1, -16, 28, -46, -61, -82, 15, -46, -5, -31, 5, 61, 52, 27, -62, 15, 22, -47, -9, -3, -17, 53, -19, -28, 28, -76, -53, -13, -11, 6, 
  -91, 12, 22, 27, 4, 74, 16, -1, 31, 45, -92, -29, -16, -5, 36, 13, 5, 26, -19, 19, 26, -44, -8, 20, -20, 37, 57, -21, -21, 7, 
};
const TfArray<2, int> tensor_dimension2 = { 2, { 4,30 } };
const TfArray<1, float> quant2_scale = { 1, { 0.016438260674476624, } };
const TfLiteAffineQuantization quant2 = { (TfLiteFloatArray*)&quant2_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[30] = { 168, 54, 66, -30, -125, -157, 148, 58, -66, -137, 147, -26, -27, -69, -127, -23, 5, 63, -6, 7, 6, 119, -42, 15, -43, -30, -117, -18, -5, -76, };
const TfArray<1, int> tensor_dimension3 = { 1, { 30 } };
const TfArray<1, float> quant3_scale = { 1, { 0.0021201912313699722, } };
const TfLiteAffineQuantization quant3 = { (TfLiteFloatArray*)&quant3_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data4[30*30] = { 
  -11, -8, -14, -17, -32, -26, 0, 15, -6, -23, -23, -13, 4, -39, -42, 36, 23, 18, 41, -5, 2, 0, 0, 22, -8, 4, -5, 24, -19, 44, 
  20, 3, 10, 5, -25, -10, 11, 25, -22, -33, -10, -48, -51, 73, 49, 7, 2, -30, -55, -62, -9, -14, -6, 1, 10, 22, -42, -12, 13, 18, 
  9, 59, 8, -26, -12, -12, 2, -17, -7, -7, 2, 38, 14, 57, 50, 20, 1, 32, -28, 39, 17, 54, 22, -19, 15, -7, -5, -11, -14, -19, 
  36, -43, 7, 4, -2, -28, 8, -2, -6, -23, 12, -2, 13, -15, 8, -6, -16, -71, -10, 8, 29, 28, -7, -1, -14, 59, -7, 20, -32, -44, 
  21, 31, -29, -30, 7, 29, 19, -26, 4, 2, -23, 5, 22, -18, -50, -40, 5, -10, 16, 37, -16, -21, 9, -24, 6, 36, -26, -7, 21, -65, 
  0, -7, 19, 23, -9, -42, -24, 23, 10, 8, 40, 31, -17, -13, -5, -36, 22, 24, -19, -11, -11, -34, 13, -19, 46, 13, 20, -42, -7, -6, 
  41, 33, 15, 6, -31, -6, -5, -27, 19, -9, -20, 10, 9, 37, 34, 2, -32, 35, -22, 47, 24, 62, 9, 18, 1, -37, -17, -16, -21, -20, 
  -22, 6, 12, 20, -41, 13, -10, -7, -30, -19, -40, -40, 2, -32, 5, -5, -44, -33, 32, 6, 6, -3, -9, 25, 36, 27, 5, 6, 7, -15, 
  -9, -41, -44, 48, -46, -16, -19, -66, 36, 20, 7, 11, 20, 45, 1, -10, 27, -20, 6, 53, 7, 22, 0, 18, 9, -21, -14, 21, 11, -41, 
  -42, -2, 6, 10, 34, 14, -16, 42, 5, 31, 15, 33, -27, -31, -16, -25, 26, -17, -7, 11, -12, -19, 8, 19, 6, 22, -3, -34, -19, 10, 
  -25, -21, -16, 19, -4, 1, 3, 9, -5, 18, -49, -31, -11, -62, -23, 15, -28, -16, 8, -9, 23, -6, 24, 17, 13, 8, 28, 40, 0, 13, 
  -6, 33, -29, 9, 28, -16, 2, -4, -127, 38, -5, -80, 5, 17, -48, 32, 35, -24, 24, -12, -1, 28, -13, -32, -30, -49, -12, 13, -4, -39, 
  -34, 28, -24, -41, 38, 7, 8, -37, 37, 12, 25, 2, -4, -19, 21, 4, 2, 13, -14, -9, 34, -22, -24, -5, 32, -25, -21, -2, 14, -1, 
  -18, 0, -1, -21, 3, -53, 15, 19, 43, -2, 14, 28, 8, -15, -2, -16, -5, 20, 13, -4, -8, -30, -15, 15, -7, 12, 28, -11, 1, -11, 
  -31, -23, -46, 38, 34, -32, 16, -15, -9, 18, 24, 33, 7, -12, 2, 20, -38, -41, -3, -62, 2, 10, -6, 40, -1, 11, -34, 15, -11, -16, 
  10, 4, -22, -10, -12, 1, 8, 11, -9, -24, -20, -29, 0, -19, 18, -9, 3, 1, 10, 1, -25, -5, 3, -5, -17, 6, 5, -12, 15, 9, 
  15, 53, 0, -22, -36, 1, 14, 1, 24, -10, -34, 44, 3, 22, 16, -8, -6, 18, 2, 12, 2, 11, 14, 4, -20, -15, -5, 1, 7, -25, 
  8, -7, 33, 49, 14, 22, 18, 29, -21, 30, -8, -29, -12, -12, -26, 4, 14, -1, -1, 4, 13, -13, 0, 35, -4, 13, 23, -11, -26, 45, 
  13, -20, 19, -2, 65, 2, -8, -7, 26, -37, 19, 21, -13, 7, -19, 31, 25, -20, -1, -31, 25, 23, 2, 8, -34, 7, 11, -10, -17, 18, 
  -8, 42, 11, 28, -52, -15, 5, 5, 11, -35, -60, 19, 1, -3, 17, -22, -3, 18, 18, 64, 2, -31, 0, 17, 29, 1, -6, 27, -12, 2, 
  -14, 1, 10, 2, -4, 6, 5, 9, -21, -15, -29, -15, -22, -16, 18, -23, -7, 13, 4, 30, -11, 9, 14, -14, 11, -8, -22, -10, -9, -10, 
  43, -21, -21, -38, -59, -24, 22, -31, 6, -7, -5, 6, -17, -21, 22, -48, 10, 29, 3, 14, 29, 21, 16, 21, -13, 7, 15, -23, 11, -26, 
  -19, 10, 13, -23, 5, -14, 4, 8, 6, -5, -3, -4, -24, -17, -4, -11, -16, -14, -26, -16, -21, 11, 21, -26, 17, -16, 13, -22, -27, -26, 
  5, -26, 15, 44, -19, 34, 1, 38, -10, -3, -21, 8, -22, -18, 11, 7, 7, -49, 16, 22, -4, -7, -15, 6, -30, 2, 2, 19, 10, 0, 
  -24, 17, -25, -43, -37, 28, -16, 0, -21, 38, -8, -32, 37, 6, 31, 17, -11, 49, -24, 10, -4, 4, 10, -26, 6, 17, 23, 18, -12, -14, 
  -8, -20, 11, -17, 28, -37, 18, -59, 8, -1, -8, 16, -41, -76, -4, -13, -17, 2, 9, -80, 27, 4, 2, 23, -30, 36, -71, -12, 10, 16, 
  15, 22, -11, 16, 8, 1, -1, -7, 8, 10, -6, 29, 4, -25, -23, -56, 7, 12, 12, 25, -18, -29, -24, -13, 50, 9, -10, -28, -9, 3, 
  17, -1, -19, 17, 0, -28, 16, 17, 13, -18, 16, -1, -15, -4, -5, -12, 0, 3, -3, 6, -29, -10, 0, -3, -9, 18, -4, -25, 2, -9, 
  -5, 5, -20, 4, 1, -11, 4, -22, -3, 23, -8, 8, 13, 4, 1, 18, 8, 15, 6, 20, -25, 3, -5, -17, -20, -9, -19, -24, -9, -16, 
  16, 39, 8, -3, -73, 22, -18, -5, 23, 47, 9, 21, 12, 64, 16, -10, -8, 4, 0, 56, -3, 14, 0, -4, 26, -16, -23, -8, 10, -32, 
};
const TfArray<2, int> tensor_dimension4 = { 2, { 30,30 } };
const TfArray<1, float> quant4_scale = { 1, { 0.012905490584671497, } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[30] = { 16, 40, 67, -131, -104, 45, -1, 17, -49, -82, -41, -49, -16, 21, 8, 35, -95, 84, -23, 14, 96, 102, 0, 84, 4, 9, -49, -5, -12, 20, };
const TfArray<1, float> quant5_scale = { 1, { 0.0026612868532538414, } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data6[30*20] = { 
  -27, 35, 34, -59, 26, -27, -15, -22, -13, 29, 20, -12, -3, -28, -7, -15, 20, -40, -2, -17, 
  -14, -5, -23, 30, 42, -44, -19, -16, 57, -43, 33, -23, -7, -6, -1, 14, 26, 28, 8, 33, 
  17, 75, -6, -39, 10, -37, -32, 22, 17, -22, -10, 18, -2, -1, 28, 4, 25, -14, 30, -2, 
  20, -8, -52, 27, -24, -45, 27, 8, 18, 24, 22, 20, -33, -1, 0, 11, -20, -16, -14, -28, 
  -25, -30, -13, -10, -8, -8, 32, -1, -37, -12, 8, 21, -22, 14, 30, -6, 49, -2, 6, 3, 
  14, 53, 5, -44, -24, -61, -9, 38, 4, -1, -42, -5, -16, 46, -20, 30, -16, 3, 51, 2, 
  22, -21, 1, -1, -22, -5, -4, -11, 15, 18, -18, -17, 1, -29, -4, -4, -20, -7, -6, -25, 
  19, 80, 31, -24, -7, -2, -5, 19, -48, 38, -30, -45, 6, -5, 16, -18, 21, -13, -53, -15, 
  -11, -22, -13, 13, 44, 15, -10, -34, 22, -63, 11, -10, 11, 28, -9, 34, 30, 26, -28, 25, 
  55, -44, -7, -64, -103, 5, 1, -33, 14, 33, -42, -26, -4, 35, 1, 34, 9, -4, 12, -26, 
  12, 47, -26, 10, 33, -19, 9, 20, 12, -14, 11, 23, -2, 19, -7, 16, 39, -9, -45, -52, 
  17, 22, -24, 0, 23, -49, -13, -41, 3, -26, -34, 16, 25, 23, 12, 22, 22, -20, 4, 46, 
  -11, -10, -4, 17, -34, -24, -13, -7, 10, 24, 47, -14, 3, 21, 22, -11, 1, 24, 21, 22, 
  5, -39, 1, 36, -47, -8, 19, -34, -42, 13, 38, 4, 29, 5, -8, -40, -23, -24, 61, -47, 
  -7, -79, 7, 40, 27, -77, 3, 25, -3, -1, 30, -13, -26, -10, 2, -30, -3, 4, 25, 21, 
  -33, -22, 20, 48, 15, -39, 28, 21, 10, 0, 63, 8, 11, 26, -3, -18, -9, -5, -35, -18, 
  23, 37, -8, 61, -10, 17, -43, 8, 1, -42, 5, 13, -10, 23, 10, -28, -33, 15, -13, 2, 
  36, 32, -59, -24, -19, 18, 3, -14, 8, -30, 17, 7, 34, 6, -6, -21, -13, 0, -33, -19, 
  6, 71, -2, -28, -50, -24, -2, 15, -17, 17, 18, -4, 37, -30, -11, -4, 40, 3, -6, -5, 
  -11, 64, 4, -5, -24, 8, 24, -42, -10, -28, -80, -10, -4, 17, -29, 5, -8, 35, 53, -36, 
  -2, -53, 1, -7, 30, -36, 28, 6, -5, -10, 30, -6, 17, -6, -1, 24, -37, 44, 11, 24, 
  4, -43, -19, -8, 44, 6, 10, 16, -26, -35, -2, -9, 26, 19, -23, -12, -45, -5, 41, -22, 
  -1, -16, -11, 13, -3, -26, -13, -31, -10, 20, -9, 19, -25, -20, 24, -31, -11, 30, -15, -1, 
  62, 57, -11, -8, 0, -33, 24, -3, -26, 3, 8, 11, 20, -22, -24, -4, 4, -3, -11, 26, 
  -8, 42, -29, 38, 16, 28, -55, -10, 18, -4, -7, 37, 8, -76, -9, -12, -29, -16, 4, -25, 
  -67, -56, -42, -41, -19, 26, 2, 9, -6, -81, -127, -20, 0, -22, -26, -15, 20, 29, 32, 0, 
  33, 60, -8, 4, -2, -42, -10, -27, -72, 49, -19, -21, 21, 25, -12, 9, 39, 6, -42, 19, 
  7, 9, 41, 42, -55, -14, 11, -16, -13, 37, 24, -13, 27, 28, -18, -17, -33, -8, 19, 16, 
  12, 8, -12, 8, -11, 25, -1, 12, -1, -20, 11, -20, -31, -14, 18, 21, 7, -25, -4, 16, 
  7, 70, 17, -6, 2, 19, 40, 7, -32, -15, -5, 39, -13, 10, -30, 17, -11, 0, -49, 6, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 30,20 } };
const TfArray<1, float> quant6_scale = { 1, { 0.011200198903679848, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data7[20] = { -2, -1, 0, 2, 5, -1, 0, 3, 1, -4, 4, 0, 1, -1, 0, -3, -5, 2, 2, 0, };
const TfArray<1, int> tensor_dimension7 = { 1, { 20 } };
const TfArray<1, float> quant7_scale = { 1, { 0.032703615725040436, } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data8[20*207] = { 
  -7, 5, 3, 3, 2, 2, 0, 2, -6, -21, -11, 1, -4, -5, -3, 1, -1, 0, -4, -4, 2, -3, 1, 1, -5, 1, -3, -3, -4, -7, 2, 1, 2, -4, -4, 1, -3, 2, -1, -3, 1, -1, -3, -1, -4, 3, -2, 3, -3, -2, -1, -4, 1, -1, -4, 3, 3, 3, 3, 2, 1, -2, 1, -3, -1, -3, 0, 1, 3, -1, -35, -37, -3, -2, -2, -2, 3, 0, -3, 1, 1, -1, -2, -1, -3, -1, -6, -3, -5, -6, -1, -3, -3, 1, -3, -6, 1, 0, -5, -2, -2, -6, -1, 0, -3, -2, -4, -2, -5, -4, 0, -2, -2, 0, -4, 1, -4, -1, -6, -1, -1, -2, -2, 1, -6, -3, 0, -2, 1, -3, -5, -4, 1, -1, 1, -4, -2, 3, 6, -19, 8, 0, -1, 3, 0, 1, -1, 2, -1, -1, -1, 3, 0, 3, 2, 0, 4, 2, -2, 2, 3, 6, 0, 1, 1, 1, 0, 0, 6, 7, 1, 3, 3, 3, 2, 7, 6, 6, 2, 2, 5, 6, 1, 2, 5, 6, 3, 1, 7, 5, 8, 2, 6, 9, 7, 7, 3, 8, 1, 5, 4, 7, 9, 6, 6, 3, 6, 
  -2, 0, 1, 1, 0, 4, 2, 4, -6, 0, 1, -3, -2, 0, 2, -2, 3, -6, 2, -3, -1, 0, 4, 3, 0, 1, -1, 2, -1, -4, 0, 4, 3, 4, 3, -1, -5, 0, 1, -1, -1, -2, 5, 2, 2, -1, 3, -3, 0, -2, -3, 0, 1, -1, 0, -4, -4, 3, 3, -3, -1, 2, -1, 0, -1, 0, 3, -3, 1, -6, -37, -78, 2, 0, 1, 6, 1, -2, 0, 6, 3, -3, -2, -1, 1, 0, 3, -3, 0, -1, 1, 1, 5, 1, 0, 2, -2, -3, 1, 0, 1, 4, 0, -1, -3, 4, 3, -3, -1, -1, -1, -3, 5, 1, -1, 3, 1, 1, -2, -3, 1, -3, -1, -2, 2, 0, 0, 2, -3, 4, -1, 0, 2, -1, 4, 2, -2, 0, 14, -41, -13, 0, -1, 7, 4, 7, 2, 1, 3, -1, -2, -2, -2, -2, -1, 3, 0, 1, -5, -3, -4, 1, 0, -3, -5, -3, -4, 1, -5, -2, -2, -4, 0, -3, -1, 1, 1, -2, -3, -3, -5, 2, 1, 1, -1, 3, 0, -1, 2, 3, 2, 1, 2, 4, -1, 1, -3, -4, -4, 4, 1, -2, -4, 0, -3, 0, 2, 
  -4, 0, 0, -4, 0, -6, 5, 7, 9, 9, 7, 9, 3, 5, 1, 6, 5, -1, 0, 2, 4, -2, 3, -2, 0, -1, 4, 2, -1, -1, -2, 3, 2, -2, 0, -1, -2, 0, 3, -2, 2, 2, -3, 0, 2, 0, -2, -2, 2, 0, 2, 0, 0, 1, 3, -2, 1, 1, 1, -1, 4, 0, 0, 1, -1, 3, 1, -2, 0, -5, -3, -9, 1, 6, 0, -3, -2, 2, -3, -3, 1, -4, 0, -1, -1, -1, -2, -1, -4, -3, -4, 1, -1, -3, 2, 1, -1, -1, 0, -1, -6, -5, -4, -5, 0, -6, 1, 1, -2, -3, -4, 0, -2, -7, -4, -5, -1, 2, -3, 0, -4, -1, 2, -6, 1, 1, -2, 0, -5, -4, 0, -5, -2, 0, -1, 0, -4, -2, -5, 18, -5, 3, 4, 10, -1, 0, -2, 1, 1, 1, 3, -1, 0, 1, 3, 5, 3, 0, 4, -2, 1, 3, 3, 5, 1, -1, 0, 1, 0, 1, -1, 1, 2, -2, 1, 3, 4, 0, 0, -1, 4, -1, 2, 6, 0, 3, 5, 0, 4, 0, 3, 3, 1, 4, 3, 0, 3, -1, 0, 3, 5, 2, 3, 1, -1, -1, 3, 
  -10, 0, 1, 3, -1, 2, -4, 4, 6, 0, 4, 6, 6, 6, 5, 2, -1, -1, 1, 3, -2, 2, -2, -4, 3, 2, -2, 3, 4, 4, -3, 1, 3, -2, 2, 0, 5, -4, 0, 2, -3, 2, -1, 4, 4, -3, 0, -2, 3, 1, -3, -1, -1, -4, 0, -4, -3, -4, -2, -1, 3, 2, 3, 2, -3, -4, 1, -4, -2, -26, 28, 1, 0, -1, 0, -1, -5, 4, 1, -1, -3, 2, 2, -1, -1, -5, -9, -3, 0, -4, -1, -1, -17, -3, 1, -5, -6, -4, -4, -10, -5, -4, 0, -6, -6, -8, -3, -5, -3, -2, -7, -4, -4, 0, -3, 0, -7, -3, -1, -3, -7, 0, -3, -2, -7, -3, -3, -5, -2, -2, -5, -7, -4, 0, -4, -5, -6, -5, -15, 32, 12, 3, 1, -10, 5, 5, 2, 1, 3, -2, 1, 0, 6, 6, 0, 3, 6, 9, 3, 1, 3, 4, 6, 5, 1, 4, 1, -1, 4, 2, -2, 0, 2, -2, 4, 3, 2, 2, 3, -3, 1, 2, 4, 3, 0, -4, -1, 2, 0, -2, 0, -3, 0, -3, 0, 3, -2, -3, -2, -2, -1, -1, -2, -2, 0, 0, 1, 
  1, -12, 2, 0, -2, 0, 7, -1, 8, 10, -2, 5, 3, 2, 0, 3, 3, 10, 2, 1, 1, 5, -1, -4, 0, 1, 4, 3, -3, -3, -1, -4, 3, -4, -2, -3, -2, -4, 0, 1, -1, 0, -6, -2, 1, -3, 2, 1, -2, 2, 1, 2, -4, -2, -2, 2, 2, 2, 2, 1, -4, -4, 1, 2, -1, 1, -3, 2, -5, -4, -20, -4, 5, 2, 1, 1, -1, 1, 1, -1, 4, -3, 6, 1, 6, 3, -2, 0, 7, -3, 3, 4, 3, 6, 5, 3, 5, -5, 1, -6, 0, -1, 2, -1, 5, -10, -2, -1, -2, 2, -3, -2, -3, -8, 1, -2, -2, -3, -6, -3, 3, -8, -3, -2, -6, -1, 2, -5, -3, -5, -2, -4, 0, -2, -3, -3, 1, -6, -43, -57, 12, 2, 2, -8, 0, -4, 6, 4, -7, -1, 2, 5, 2, 0, 3, 4, 7, 1, 7, 0, 1, 2, -3, 0, -3, -2, 1, -4, 5, -1, -1, -4, -4, 1, -1, -1, -3, 0, -3, 0, -3, -3, -1, -1, -2, -6, -5, -4, 1, -5, 1, -4, -1, -4, -5, 0, -3, -4, -3, -6, -4, 1, -2, -6, -5, -6, -5, 
  -1, 4, -3, -1, -3, -4, 0, 3, -2, 3, -3, -3, -5, 2, 1, 0, -3, 1, -1, 1, -2, -3, 0, -1, 3, 0, 2, 0, -1, 5, 0, 0, 4, -2, 1, -3, 3, -2, 2, 4, 3, 2, -2, -1, 1, -3, -2, -2, 1, 3, 4, 0, 2, -1, 2, 3, 2, 0, 3, 1, 2, -3, 3, -2, 0, 1, -1, 4, 4, -1, 2, 3, 2, -4, -5, -3, -1, -1, 2, -1, -4, 1, -2, 2, -1, -3, 1, -1, 3, 1, 0, 0, -3, 3, 0, 0, -1, 2, 0, 3, 0, 2, 4, -2, 2, 2, 5, -1, 3, 4, 1, 1, 3, 4, 4, 2, 3, -2, 2, -1, -3, 4, -2, 1, 1, 4, 0, -1, -1, -2, 1, 2, -2, -1, 1, 4, 2, -2, 2, -3, 7, 0, 1, -3, 0, -3, 3, 3, 2, -2, 3, 2, 2, -3, 3, -1, -2, 2, -2, -1, 2, -4, 1, -4, 2, -5, 3, -3, 1, -1, -1, 2, -4, -1, -4, 0, -4, -2, 2, 1, 2, 0, -5, -4, -2, -4, -1, -3, 2, -5, -4, 2, 0, -1, -1, -4, 2, -2, 1, -2, -2, 0, 1, 1, -5, -5, -5, 
  -6, -9, -2, -1, -1, -4, -8, -4, -8, -2, 0, -27, -15, -7, -6, -7, -8, -6, -1, -2, -6, -3, -5, 0, -6, -4, 0, -7, -1, -2, 2, -5, -2, -3, -5, 0, -6, -1, -5, 2, -2, -1, 0, -3, -5, -6, 1, -5, -3, -3, -5, 1, -5, 0, -1, -1, -2, 1, 0, -4, -5, -3, 2, -4, 0, -1, -5, 1, -5, -6, 2, 12, -2, 1, -4, 1, -2, 3, 1, -3, 5, 0, 0, 0, -2, -1, 4, 0, -2, -6, -3, 1, -1, 4, -1, -5, -2, -8, -4, 0, -2, -1, 0, -2, 4, -5, 0, -4, -2, 1, 0, 1, 3, -9, 1, -2, 2, -1, -2, -2, -2, -5, -3, -1, -1, -2, 0, 1, -1, -9, 2, -4, 0, 3, 3, 2, -3, -3, 9, 0, -5, 2, -1, -1, 5, 6, 4, -2, 9, 5, -2, 4, 1, 4, 0, -2, 1, -1, 3, -1, 5, 6, 0, -2, 4, 0, -1, 5, 5, 2, -3, 4, 4, 5, 5, -2, -2, 0, 3, 1, 5, 2, 5, 2, 0, -2, 4, -1, -1, -1, 4, 0, 4, 2, -2, 0, 4, 5, 1, 2, 0, -1, 0, -1, 1, 5, 7, 
  7, -16, 2, 4, 2, 3, 5, 5, 3, 8, 0, 7, 1, 2, -3, -6, -4, 3, -1, 4, 3, -3, -3, -5, 0, 4, -1, 1, -4, -2, 0, 2, 0, -5, -3, -5, -2, 0, 1, -3, -2, -1, 1, 2, 0, -2, -1, -5, -4, 1, -4, -2, -2, -1, -3, -4, -5, 1, 1, -5, -4, -3, 0, -4, 0, 0, -1, -3, -3, -2, -14, 2, 0, 1, 1, 3, -1, 4, -1, 4, 5, -3, 3, 0, 1, -4, 3, 2, 2, -1, -1, -4, 0, -3, -4, -3, -2, -4, -1, 2, -3, 1, -2, -5, -2, -3, -4, -6, 1, -4, -4, -5, -2, -1, 0, -4, 0, -4, -4, -2, -4, -2, -4, -6, -1, -2, -6, -7, -4, -4, -1, -4, -4, -3, -6, -1, -4, -4, -9, -99, 8, 2, -2, 12, 0, 1, 1, -2, 3, 3, 4, 0, 2, 4, 4, 3, 0, 2, 1, 0, 1, -3, 2, 0, 0, 0, -3, 2, -3, 0, 3, -1, -1, 1, -4, 2, -2, -4, -2, -1, -1, 3, -1, -2, -3, 0, 1, 2, 3, 0, -4, -2, 2, 3, -2, 0, 3, 2, -3, 1, -3, -1, -3, -1, -2, 3, -3, 
  -2, 5, 4, 0, -2, 1, -4, -6, -4, -7, 4, 5, 4, 0, 1, -2, 1, -2, 4, 1, 4, 3, 3, 2, 2, 2, 2, -1, 2, -5, 3, -3, 0, 0, -3, -1, -3, 3, -3, 0, -2, -2, -4, -2, -4, 1, -2, -1, -3, 1, -4, -4, 4, -3, 2, 1, 0, 1, -1, -2, 2, -2, 4, -2, 0, -4, 3, 2, 2, -4, 38, 1, -2, -9, -2, -3, -1, -2, -3, 2, -3, -3, -4, -3, 1, -2, -3, -2, -2, -3, -6, -11, -16, -8, -4, -7, -3, -5, -6, -6, -7, -7, -6, -2, -4, -2, -5, -4, -3, -4, -6, -2, -3, -2, -1, 0, -2, -6, -1, -5, -1, 0, -3, -5, -2, -7, -3, 0, -7, 0, -7, 0, -7, -4, -6, -3, -6, 0, -4, -19, 9, 1, 4, -4, -2, 2, 2, -2, -3, -1, 5, 4, 0, 0, 0, 4, -2, -2, 3, 0, 2, -1, 0, -4, -2, -5, -5, 0, 0, -1, 2, -2, -1, 1, 1, -3, 1, -3, -5, 0, -5, -3, -4, -3, -1, 0, -4, -3, -5, 1, 1, 0, -1, 1, -5, 0, -2, -3, -5, 2, 1, 0, -3, -2, 0, -2, -1, 
  -22, -7, 3, -2, -2, -2, -5, -1, -3, 3, 8, -20, -14, -7, -7, 0, -3, 1, 2, -3, -1, 2, 0, 4, 5, 4, 1, 2, 1, 4, -3, -1, -2, 1, 3, 2, 4, 4, 0, 2, 2, 3, 0, 2, -1, -3, 4, 3, 5, -1, 3, 5, -3, -3, -1, 2, 4, 2, -2, 3, -2, -1, -1, 4, 1, 0, -2, 0, -1, -7, -24, -2, 2, 0, -2, -5, 1, -3, -6, 1, 0, 2, -5, -4, -5, 1, -4, -4, 0, -1, 2, 0, -2, -1, 0, 3, -1, -4, -3, -2, 2, -3, -4, -1, 1, 0, -4, -2, 2, 2, 2, -1, -1, -1, 4, 3, 4, 3, 4, 3, 4, -3, -1, 4, -1, 3, 4, 0, 0, 3, 0, -1, 0, 0, -2, 3, 5, 2, 1, -6, 19, -3, 4, 3, 1, 1, 3, -1, -4, -2, -5, -4, -3, -3, 3, -4, -3, 2, -3, -1, -1, -3, 2, 2, 1, -3, 0, -1, 1, -1, 2, 4, 4, 1, -2, 0, 2, -1, 5, 2, -1, 2, 5, 6, 4, 0, 7, 5, 2, 3, 4, 1, 1, 7, 4, 0, 2, 2, 0, 3, 5, 4, 1, 2, 5, 6, 6, 
  -6, 4, 4, -1, -2, 0, 3, -3, -5, -12, -10, 11, 2, -4, 0, -5, -4, -4, 0, 0, -4, 0, -6, -2, 2, -2, -3, -3, 1, -1, -6, -5, -5, -2, 2, 2, -3, -5, -5, -1, -1, -3, -3, -3, -3, 1, -1, -5, 0, -2, -3, -4, -3, -2, 1, 0, -4, -3, -1, -2, -1, -1, 0, 1, -1, -6, -5, 0, 0, 1, 25, 13, -1, -5, 2, 6, 4, -1, 3, 4, -1, -2, 2, -1, -1, 3, -2, 1, -1, -2, 0, 3, 0, -3, -2, -2, -5, -2, -7, -2, 0, -1, -2, -2, -2, -8, -4, -8, -1, -4, -5, -5, -3, -3, -8, -4, -6, -1, -6, -7, -7, -8, -7, -8, -2, -3, -8, -4, -3, -9, -3, -7, -8, -9, -4, -4, -5, -10, 10, 27, -21, -2, -4, 3, 2, -2, 4, 3, 6, 2, 4, 7, 7, 9, 3, 2, 4, 6, 5, 6, 9, 2, 9, 7, 5, 5, 6, 2, 3, 4, 6, 2, 1, -1, 5, 5, 4, 2, 3, 6, 3, -3, 3, -2, 0, 4, -2, 2, 5, 1, -2, -3, 3, -3, 1, 2, 0, -2, -3, 0, 2, 4, 2, -1, -1, 3, 1, 
  21, -6, 6, 0, -2, 5, 6, 4, 9, 8, 7, 1, 5, 9, 6, 9, 6, 1, 8, 5, 4, 4, 8, 7, 5, 5, 6, 6, 8, 5, 3, 2, 3, 2, 4, 2, 0, 4, 4, 5, 5, 6, 8, 1, 0, 1, 3, 4, -1, 1, 0, 5, 4, 4, 6, 4, 4, 2, 3, -1, 5, 4, 3, 2, 5, 5, 5, 2, 2, 0, -9, 2, 0, 2, 1, 0, -2, 3, 2, 1, 3, 3, -3, -2, -3, -3, -1, 2, 0, 0, 2, -3, -3, -2, 1, 1, 2, 0, 0, -1, 0, 0, 3, 2, 2, 0, 0, 3, 0, -3, -1, 0, 2, -2, -4, -3, -3, 1, 3, 1, 4, 0, 0, -2, 0, -1, -2, -4, 4, 0, -2, 1, 2, -1, -3, 0, -3, 2, 7, -9, -1, 2, 2, 3, 5, -2, 0, -2, 0, 0, 3, -2, 0, 1, 0, 4, 2, 4, -1, -1, 4, 0, 1, 2, -3, 2, -2, -3, 5, 2, 2, 1, 4, -1, 5, 0, 4, 4, -1, 3, 0, 3, 1, 3, -2, 1, 0, 1, 3, 2, -4, -1, -1, -4, -1, 3, 2, 2, -4, -2, 0, -3, 4, -3, -3, 2, -1, 
  7, -11, 2, -2, 1, 3, 2, 1, -3, 7, 7, -4, 2, 5, 1, 5, 2, -1, 4, 0, 3, 3, -1, 4, 2, -1, 1, -1, 3, 0, -1, 2, -3, 4, 3, 3, 3, -2, -3, -2, 0, 1, -2, -2, -4, -1, 4, 2, 0, 4, 3, -3, -4, 1, -2, -3, -2, 1, -1, 2, -1, -3, -2, 3, 1, 1, 3, 2, 0, -5, -4, 7, 1, 0, 3, -3, 0, 4, -2, -2, 3, 3, 5, 4, 5, 5, -2, -1, 2, 3, -1, 5, 3, 2, -1, -2, 3, 1, 4, 1, -1, 4, 4, 3, 2, -2, 2, 5, 4, 2, 2, 0, 2, -1, -1, 2, 0, 1, 6, 4, 4, 1, 3, 0, 3, 4, -2, 4, 0, 4, 2, 4, 5, 2, 3, 5, 4, 1, 12, 67, -20, 2, 4, 1, 4, 4, -2, 4, 3, -2, 2, -2, 1, 2, 1, 5, -2, 3, -1, -1, 3, 1, -3, -1, -2, -3, 0, 4, -1, -2, 4, -2, -3, 1, 2, 2, -1, 1, -2, -4, -2, -1, -1, 0, 3, -2, -2, -3, -2, -3, 0, 4, 1, 3, -2, 4, -1, 1, -2, -2, 1, 2, -3, 3, 0, -4, 1, 
  2, -9, -2, -1, 2, 5, -9, -1, -2, 3, 5, -17, -7, -4, -3, -3, -3, -4, -5, -2, -3, -3, 1, 3, -4, -5, -3, 3, -1, 0, 1, -3, -3, -4, 0, 1, 1, 0, 3, -1, 4, 3, 5, -4, 3, -2, 0, 2, 4, 1, 1, 2, -3, -2, 4, -1, 0, 3, 2, -1, 0, -2, 0, -2, 3, 3, 3, 3, 0, 8, 10, -10, 2, -1, -2, -4, -5, -3, 1, -3, -1, 0, -2, -2, 1, 0, 1, 1, -2, -7, -1, -1, -4, 1, -6, -5, -4, -1, -2, -3, -1, 2, -1, -5, -4, -2, -2, -3, -3, 0, 1, -6, -3, -3, -4, 0, 1, -3, 0, -6, -2, -6, -3, -3, 1, -1, -5, 1, 0, -1, -5, -5, 0, -1, -5, -6, 0, -5, 7, 13, 10, -1, 3, -10, 5, 8, 2, -2, 6, 5, -1, -2, -3, -3, 0, 5, -2, 0, 2, -1, 0, 7, 2, 1, 1, 1, 2, -2, -1, -1, 4, -1, 2, 2, 0, -2, 2, 3, 0, 1, 4, -1, -1, 2, 2, 2, -3, 3, 5, 4, 0, -2, 3, 5, 0, 1, -2, 0, 3, -2, 0, 1, 2, 3, 4, 2, 3, 
  3, -3, -2, 1, 0, -2, -2, 1, 2, 1, 4, -4, -3, 4, -4, -1, -3, 1, 2, -3, 3, 4, -2, 3, -4, -2, 0, -3, 3, -1, 4, -2, -2, 2, -1, -2, -3, 1, 3, -3, -4, 3, -4, 3, -1, 2, -1, -2, -4, -2, -1, 2, 1, -1, -3, -2, 4, -1, 3, -2, 0, 2, -2, 4, 1, 4, 3, 2, -1, 2, 0, -2, 3, -2, 3, 2, -2, 1, 0, 0, 2, 0, -3, -2, 1, -3, 3, 0, -3, 1, -2, 1, -1, 2, -3, 0, 3, 3, 3, 4, -4, 3, -3, 3, -3, -1, 2, -4, -2, -2, -2, 0, 4, 2, -4, 2, 4, -3, 3, 3, -2, -1, -1, -2, -3, -3, 0, 4, 3, -3, -1, -2, 0, 0, 2, 2, 3, 2, -3, 3, -1, 1, -1, -2, 3, 2, 1, -2, 2, 3, -1, -3, 3, 2, 2, -2, -1, 2, -1, -3, 1, 2, 0, -1, -3, -2, 1, 1, 3, -2, 2, 2, -2, -2, -3, 2, 3, 2, 1, 2, -4, -3, -3, 0, 1, 1, 0, 1, 3, 1, -3, 0, -2, 3, -1, -1, -3, 1, 2, 3, 3, -4, 3, -2, -4, 2, -4, 
  -5, 13, 1, -4, -2, 0, -5, -4, -1, 1, -7, 1, -3, 0, 1, 2, -1, 2, 2, 3, -3, 4, -3, 5, 2, 1, -1, 0, 0, -2, 2, 0, 0, 3, 1, 2, 2, -2, 2, 5, 4, 0, 4, -1, 4, -1, -2, 0, -2, 4, 3, 1, 4, 5, 3, 0, 5, 3, -1, 5, 2, -1, 3, 0, 2, 3, 2, -1, 2, 10, 4, 1, 2, 3, 0, 2, -3, -1, 1, -1, -4, -4, -1, 2, 2, 1, -1, 0, 1, 2, -2, 2, -1, 1, 2, 1, -5, 0, 0, 1, 2, 2, 2, -3, 1, -4, -1, 0, 3, -3, 0, -5, -5, -1, 1, -4, -2, -4, -1, -2, -3, -1, -2, -3, 0, -2, -3, -3, -2, -4, -2, -2, 0, 2, -4, -3, -3, -2, 4, -55, 7, 0, -2, 2, 2, 1, 3, 0, -1, -3, 2, -1, -1, 4, 3, 3, -1, 4, 0, -1, 0, 6, -1, 4, 3, 2, -1, 6, 5, 3, 3, 2, 2, 1, 6, 8, 4, 1, 1, 4, 9, 3, 3, 3, 4, 6, 5, 4, 6, 2, 3, 8, 7, 3, 8, 3, 3, 3, 8, 8, 9, 10, 6, 5, 10, 7, 8, 
  -4, -3, -3, -3, 2, -2, -9, -9, -10, -7, -8, -27, -13, -7, -7, -4, -7, -4, 0, -3, -4, -4, 1, 0, 1, -1, -1, 3, -3, 3, 3, 1, 4, -2, 0, -1, 1, -2, 0, 1, 1, 1, 4, 3, 1, -2, 4, -3, 0, -2, 2, 1, 1, -2, 1, -4, 0, 0, 4, -2, -1, 4, 0, 2, -1, 3, 2, 0, 0, 10, -10, -6, -4, 3, -2, 0, -5, -1, -5, -2, 0, 1, -6, -4, -2, 1, -1, -5, 2, -4, -1, 2, 3, 0, 0, -3, -1, -4, 2, -2, -1, -1, -1, -1, 3, 2, 2, 3, 0, -2, 3, 1, 3, -5, -3, 1, 0, 5, -1, -3, 3, -1, -1, 0, 5, 2, 1, -3, 5, 3, 1, 4, 1, 2, -1, 1, 4, -2, 15, -127, 9, -3, 1, -1, -3, 2, 0, -1, -1, -2, -6, -4, -1, -2, -3, -4, -1, 0, -6, -4, -6, 1, -4, 0, 0, -5, 1, -5, -4, -2, 0, -3, 0, 1, 0, -2, 0, 2, -5, 2, 2, -2, -4, 1, 3, -2, -3, 3, -4, 2, 4, -3, -2, 5, 4, 3, 1, -2, -1, 2, -3, 2, -3, -1, 4, 2, -3, 
  4, 12, 1, 3, 2, -2, 3, 6, 12, 12, 10, 25, 11, 9, 2, 3, 3, -3, 2, -3, 2, -2, -3, 7, -3, -4, -3, 1, -1, -2, -1, -4, -1, 0, 0, 3, 5, -3, 2, -4, -4, -2, 3, -1, 1, -3, 0, 3, -3, 2, -3, -3, 2, 1, 0, -3, 2, -4, -2, -3, 0, -3, 1, 3, -2, 1, -1, -1, 2, 3, 4, -11, 3, 4, 5, 2, -1, -2, 3, -4, -4, -1, -3, 2, 3, 4, -3, 2, 1, 5, 0, 5, -5, -2, 3, 3, 2, 2, 3, -4, 3, 1, 0, -2, -3, -2, -4, 4, 0, -5, -5, -3, 2, 4, -4, 1, 1, 2, -5, -1, -4, 7, 0, 3, -3, 0, 0, 3, 2, 7, 1, 0, -4, 1, -1, -1, 2, 4, -8, 46, -4, -4, -5, 1, 4, 0, 4, 4, 4, 0, 3, 4, -3, -2, 2, 0, 0, 3, 3, -1, -2, -4, -2, 1, 4, 4, -2, -1, 4, 2, -3, 0, 3, 3, 5, 4, 1, 1, -1, 3, 5, 2, 3, -2, -4, 1, 3, -2, 0, -4, 2, 2, -1, 2, 3, -4, 0, 2, 1, -3, 0, -2, 0, -3, 0, -2, 2, 
  -9, 4, 2, -4, 1, -5, -1, 1, 4, -7, -13, 18, 8, 3, 0, 1, 2, 2, 0, 3, -1, 4, -2, 0, -1, -3, 0, -1, -3, -3, 0, -2, -3, -4, 3, 2, 2, -3, -4, -2, -3, 0, -6, 2, 0, -1, 3, 1, -3, -3, 0, -4, 1, -3, 2, -3, -3, -3, -2, 2, -2, -2, -4, 2, 1, -3, 2, -4, 1, 8, 6, -2, 4, 0, 1, 3, 6, 2, 0, 2, 0, 5, 4, 1, 3, 1, 3, 2, 0, 2, -3, 5, 2, -1, -2, -1, 2, 7, 4, -2, -4, 3, 1, 2, -2, 6, -2, -1, 0, 1, -3, 2, -5, 5, -3, -2, 1, 0, -4, -2, 3, 5, -2, 2, 0, 2, -2, -1, -1, 7, -4, -1, -1, -2, -1, -1, 0, 10, -19, 119, 8, 0, 0, -7, -3, -4, 0, 1, -4, -2, 0, 2, 4, 2, 0, -3, 3, -1, 5, 0, 1, -4, 2, -2, 0, -3, -1, 4, 0, 3, 4, -2, 4, 3, 0, 2, -2, -2, 3, 2, 1, -3, -4, 3, 2, -3, -4, -4, -1, 0, 0, 0, -2, -4, 0, -2, -2, -2, 2, -4, 2, -4, -2, 1, -2, -3, -3, 
  4, 7, -2, -2, -1, -3, 1, 2, 8, 5, -1, 14, 8, 1, 0, -2, -1, 0, -2, 1, -2, -4, 1, -6, 1, 1, -2, -2, 1, 4, -3, 0, 3, -3, 0, 1, -2, 0, 0, -1, -3, -3, 0, 3, 0, -3, -4, 1, 0, 1, 0, 1, -4, 1, 1, -3, 3, -3, -3, 3, -3, 3, -4, 1, -3, -1, -1, -3, -2, -1, -7, 17, 0, 1, 0, 0, -3, -5, -5, -6, -2, 0, -2, -5, -3, -3, -2, -2, -2, 4, -8, -3, -16, -8, -6, -9, -10, 6, -4, -13, -8, -3, -3, -7, -5, 2, -8, -6, -5, -2, 0, -1, -8, -1, -2, -2, -4, -6, -5, -2, 1, 2, -1, -4, -2, -1, -6, -2, -5, 1, -6, -3, 0, -1, -2, 2, -1, 3, -13, 81, 7, -2, 3, -2, -4, -1, -3, 3, -5, -5, -7, -2, -5, -6, -5, -11, -8, -6, -5, -6, -13, -28, -3, -7, -6, -10, -2, -5, -4, -7, -6, -2, -3, -5, -3, -2, -7, -3, -5, -4, -1, -8, -4, -4, -5, -2, -6, -5, -4, 0, -4, -4, 1, -3, -2, 0, -6, -6, 1, -7, 0, -6, -2, 0, -1, -3, -5, 
};
const TfArray<2, int> tensor_dimension8 = { 2, { 20,207 } };
const TfArray<1, float> quant8_scale = { 1, { 0.041860565543174744, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const TfArray<2, int> tensor_dimension9 = { 2, { 1,20 } };
const TfArray<1, float> quant9_scale = { 1, { 0.23761066794395447, } };
const TfArray<1, int> quant9_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&quant9_zero, 0 };
const TfArray<2, int> tensor_dimension10 = { 2, { 1,30 } };
const TfArray<1, float> quant10_scale = { 1, { 0.16428598761558533, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant9_zero, 0 };
const TfArray<1, float> quant11_scale = { 1, { 0.16705921292304993, } };
const TfLiteAffineQuantization quant11 = { (TfLiteFloatArray*)&quant11_scale, (TfLiteIntArray*)&g0::quant9_zero, 0 };
const TfArray<2, int> tensor_dimension12 = { 2, { 1,4 } };
const TfArray<1, float> quant12_scale = { 1, { 0.70752137899398804, } };
const TfArray<1, int> quant12_zero = { 1, { 46 } };
const TfLiteAffineQuantization quant12 = { (TfLiteFloatArray*)&quant12_scale, (TfLiteIntArray*)&quant12_zero, 0 };
const TfArray<1, float> quant13_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant13 = { (TfLiteFloatArray*)&quant13_scale, (TfLiteIntArray*)&g0::quant9_zero, 0 };
const TfLiteFullyConnectedParams opdata0 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs0 = { 3, { 0,8,7 } };
const TfArray<1, int> outputs0 = { 1, { 9 } };
const TfLiteFullyConnectedParams opdata1 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs1 = { 3, { 9,6,5 } };
const TfArray<1, int> outputs1 = { 1, { 10 } };
const TfLiteFullyConnectedParams opdata2 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs2 = { 3, { 10,4,3 } };
const TfArray<1, int> outputs2 = { 1, { 11 } };
const TfLiteFullyConnectedParams opdata3 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs3 = { 3, { 11,2,1 } };
const TfArray<1, int> outputs3 = { 1, { 12 } };
const TfLiteSoftmaxParams opdata4 = { 1 };
const TfArray<1, int> inputs4 = { 1, { 12 } };
const TfArray<1, int> outputs4 = { 1, { 13 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension0, 207, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant1))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 120, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant2))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 120, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant3))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 900, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant4))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension3, 120, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 600, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data7, (TfLiteIntArray*)&g0::tensor_dimension7, 80, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data8, (TfLiteIntArray*)&g0::tensor_dimension8, 4140, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 208), (TfLiteIntArray*)&g0::tensor_dimension9, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 32), (TfLiteIntArray*)&g0::tensor_dimension10, 30, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension10, 30, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant11))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 32), (TfLiteIntArray*)&g0::tensor_dimension12, 4, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant12))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension12, 4, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[5] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[5] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 14, };
const size_t tflNodes_subgraph_index[] = {0, 5, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  13, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_664951_3_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 14;
  for (size_t i = 0; i < 14; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_664951_3_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_664951_3_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_664951_3_invoke() {
  for (size_t i = 0; i < 5; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_664951_3_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
